server:
  port: 9002
spring:
  application:
    name: tansquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.64.128:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true